auth:
  secretKeys:
    adminPasswordKey: postgres-password
  existingSecret: wrenai-postgresql

global:
  postgresql:
    auth:
      database: admin_ui
image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: "16.3.0-debian-12-r14"
  pullPolicy: IfNotPresent

# Add this section:
primary:
  persistence:
    enabled: true
    storageClass: gp2
    size: 8Gi
  nodeSelector:
    if-wren-ai-pod: 'true'
  tolerations:
    - key: "if-wren-ai-pod"
      value: "true"
      effect: "NoSchedule"
    - key: "if-monitoring-pod"
      value: "true"
      effect: "NoSchedule"         