# you should rename this file to config.yaml and put it in ~/.wrenai
# please pay attention to the comments starting with # and adjust the config accordingly

type: llm
provider: litellm_llm
timeout: 120
models:
# put GEMINI_API_KEY=<your_api_key> in ~/.wrenai/.env
- model: gemini/gemini-2.0-flash-exp  # gemini/<gemini_model_name>
  kwargs:
    n: 1
    temperature: 0
- model: gemini/gemini-2.0-flash-exp  # gemini/<gemini_model_name>
  alias: gemini-llm-for-chart
  kwargs:
    n: 1
    temperature: 0
    response_format:
      type: json_object

---
type: embedder
provider: litellm_embedder
models:
# put GEMINI_API_KEY=<your_api_key> in ~/.wrenai/.env
- model: gemini/text-embedding-004  # gemini/<gemini_model_name>
  api_base: https://generativelanguage.googleapis.com/v1beta/openai  # change this according to your embedding model
  timeout: 120

---
type: engine
provider: wren_ui
endpoint: http://wren-ui:3000

---
type: document_store
provider: qdrant
location: http://qdrant:6333
embedding_model_dim: 768  # put your embedding model dimension here
timeout: 120
recreate_index: true

---
# please change the llm and embedder names to the ones you want to use
# the format of llm and embedder should be <provider>.<model_name> such as litellm_llm.gpt-4o-2024-08-06 or <provider>.<alias> such as litellm_llm.gemini-llm-for-chart
# the pipes may be not the latest version, please refer to the latest version: https://raw.githubusercontent.com/canner/WrenAI/<WRENAI_VERSION_NUMBER>/docker/config.example.yaml
type: pipeline
pipes:
  - name: db_schema_indexing
    embedder: litellm_embedder.gemini/text-embedding-004
    document_store: qdrant
  - name: historical_question_indexing
    embedder: litellm_embedder.gemini/text-embedding-004
    document_store: qdrant
  - name: table_description_indexing
    embedder: litellm_embedder.gemini/text-embedding-004
    document_store: qdrant
  - name: db_schema_retrieval
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    embedder: litellm_embedder.gemini/text-embedding-004
    document_store: qdrant
  - name: historical_question_retrieval
    embedder: litellm_embedder.gemini/text-embedding-004
    document_store: qdrant
  - name: sql_generation
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: sql_correction
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: followup_sql_generation
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: sql_summary
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: sql_answer
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: sql_breakdown
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: sql_expansion
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: sql_explanation
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: sql_regeneration
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: semantics_description
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: relationship_recommendation
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: question_recommendation
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: question_recommendation_db_schema_retrieval
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    embedder: litellm_embedder.gemini/text-embedding-004
    document_store: qdrant
  - name: question_recommendation_sql_generation
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    engine: wren_ui
  - name: chart_generation
    llm: litellm_llm.gemini-llm-for-chart
  - name: chart_adjustment
    llm: litellm_llm.gemini-llm-for-chart
  - name: intent_classification
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
    embedder: litellm_embedder.gemini/text-embedding-004
    document_store: qdrant
  - name: data_assistance
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: sql_pairs_indexing
    document_store: qdrant
    embedder: litellm_embedder.gemini/text-embedding-004
  - name: sql_pairs_retrieval
    document_store: qdrant
    embedder: litellm_embedder.gemini/text-embedding-004
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: preprocess_sql_data
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: sql_executor
    engine: wren_ui
  - name: sql_question_generation
    llm: litellm_llm.gemini/gemini-2.0-flash-exp
  - name: sql_generation_reasoning
    llm: litellm_llm.gemini/gemini-2.0-flash-exp

---
settings:
  column_indexing_batch_size: 50
  table_retrieval_size: 10
  table_column_retrieval_size: 100
  allow_using_db_schemas_without_pruning: false  # if you want to use db schemas without pruning, set this to true. It will be faster
  query_cache_maxsize: 1000
  query_cache_ttl: 3600
  langfuse_host: https://cloud.langfuse.com
  langfuse_enable: true
  logging_level: DEBUG
  development: true
