name: AI Service Release stable image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Give a version for this release
        type: string
        required: true

defaults:
  run:
    working-directory: wren-ai-service

jobs:
  upgrade-ai-service-version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
      - name: Set up Git
        run: |
          git config --global user.name "wren-ai[bot]"
          git config --global user.email "dev@cannerdata.com"
      - name: Set up Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.3
      - name: Generate and Save Change Log
        id: changelog
        run: |
          echo "Generating change log..."
          PREVIOUS_VERSION=release/ai-service/$(poetry version -s)
          echo "Previous version: $PREVIOUS_VERSION"
          CHANGE_LOG=$(git log --pretty=format:"%s" $PREVIOUS_VERSION..HEAD | grep wren-ai-service)

          # Separate the change log into categories
          FEATURES=$(echo "$CHANGE_LOG" | grep "^feat" | sed 's/^/- /')
          FIXES_AND_CHORES=$(echo "$CHANGE_LOG" | grep -E "^(fix|chore)" | sed 's/^/- /')

          # Create the full change log
          FULL_CHANGE_LOG="\nChangelog for the version\n"
          if [ -n "$FEATURES" ]; then
            FULL_CHANGE_LOG+="\nFeature and Enhancement\n$FEATURES"
          fi
          if [ -n "$FIXES_AND_CHORES" ]; then
            FULL_CHANGE_LOG+="\n\nFixes and Chores\n$FIXES_AND_CHORES"
          fi

          {
            echo "CHANGE_LOG<<EOF"
            echo -e "$FULL_CHANGE_LOG"
            echo EOF
          } >> $GITHUB_ENV
      - name: Upgrade AI Service version
        run: |
          version=${{ github.event.inputs.version }}
          poetry version --next-phase $version
          git add pyproject.toml
          git commit -m "Upgrade AI Service version to $version"
          git push
          git tag -a "release/ai-service/$version" -m "${{ env.CHANGE_LOG }}"
          git push origin "release/ai-service/$version"
  build-image:
    needs: upgrade-ai-service-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/canner/wren-ai-service
          tags: |
            type=raw,${{ github.event.inputs.version }}
            type=raw,latest
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          context: ./wren-ai-service
          file: ./wren-ai-service/docker/Dockerfile
