name: Wren-UI Build image

on:
  workflow_dispatch:
    inputs:
      docker_image_tag_name:
        description: Docker image tag name (Optional)
        type: string
      is_latest:
        description: Is latest (Optional)
        type: boolean
        required: false
        default: false

defaults:
  run:
    working-directory: wren-ui

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare tag name
        id: tag-preparation
        run: |
          if [ -n "${{ github.event.inputs.docker_image_tag_name }}" ]; then
            tag_name=${{ github.event.inputs.docker_image_tag_name }}
          else
            tag_name=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9]/-/g')-$(git log -1 --pretty=%h)
          fi
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
      - name: Build and push image
        env:
          TAG_NAME: ${{ steps.tag-preparation.outputs.TAG_NAME }}
        run: |
          if [ ${{ github.event.inputs.is_latest }} == true ]; then
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag ghcr.io/canner/wren-ui:$TAG_NAME \
              --tag ghcr.io/canner/wren-ui:latest \
              --file ./docker/Dockerfile \
              --push .
          else
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag ghcr.io/canner/wren-ui:$TAG_NAME \
              --file ./docker/Dockerfile \
              --push .
          fi